// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: desktopviaclyde/v1/daemon/service.proto

package desktopviaclydev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DesktopService_GetStatus_FullMethodName          = "/desktopviaclyde.v1.DesktopService/GetStatus"
	DesktopService_RunUpgrade_FullMethodName         = "/desktopviaclyde.v1.DesktopService/RunUpgrade"
	DesktopService_RunPatch_FullMethodName           = "/desktopviaclyde.v1.DesktopService/RunPatch"
	DesktopService_RunHardReset_FullMethodName       = "/desktopviaclyde.v1.DesktopService/RunHardReset"
	DesktopService_RunKeychainMigrate_FullMethodName = "/desktopviaclyde.v1.DesktopService/RunKeychainMigrate"
	DesktopService_SubscribeActive_FullMethodName    = "/desktopviaclyde.v1.DesktopService/SubscribeActive"
	DesktopService_GetUpdaterStatus_FullMethodName   = "/desktopviaclyde.v1.DesktopService/GetUpdaterStatus"
)

// DesktopServiceClient is the client API for DesktopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DesktopService is the daemon control plane. The daemon owns all operation
// logic; the CLI is a thin client that invokes these RPCs and renders the
// streamed ProgressEvent values through the same live model used for local
// runs. A Run* call either starts the operation or, when one is already in
// flight for the same target and operation, streams that run's events instead.
// Distinct targets can run at the same time, while conflicting mutations for
// the same target are rejected.
type DesktopServiceClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	RunUpgrade(ctx context.Context, in *RunUpgradeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressEvent], error)
	RunPatch(ctx context.Context, in *RunPatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressEvent], error)
	RunHardReset(ctx context.Context, in *RunHardResetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressEvent], error)
	RunKeychainMigrate(ctx context.Context, in *RunKeychainMigrateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressEvent], error)
	SubscribeActive(ctx context.Context, in *SubscribeActiveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressEvent], error)
	GetUpdaterStatus(ctx context.Context, in *GetUpdaterStatusRequest, opts ...grpc.CallOption) (*GetUpdaterStatusResponse, error)
}

type desktopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDesktopServiceClient(cc grpc.ClientConnInterface) DesktopServiceClient {
	return &desktopServiceClient{cc}
}

func (c *desktopServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, DesktopService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopServiceClient) RunUpgrade(ctx context.Context, in *RunUpgradeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DesktopService_ServiceDesc.Streams[0], DesktopService_RunUpgrade_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunUpgradeRequest, ProgressEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DesktopService_RunUpgradeClient = grpc.ServerStreamingClient[ProgressEvent]

func (c *desktopServiceClient) RunPatch(ctx context.Context, in *RunPatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DesktopService_ServiceDesc.Streams[1], DesktopService_RunPatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunPatchRequest, ProgressEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DesktopService_RunPatchClient = grpc.ServerStreamingClient[ProgressEvent]

func (c *desktopServiceClient) RunHardReset(ctx context.Context, in *RunHardResetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DesktopService_ServiceDesc.Streams[2], DesktopService_RunHardReset_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunHardResetRequest, ProgressEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DesktopService_RunHardResetClient = grpc.ServerStreamingClient[ProgressEvent]

func (c *desktopServiceClient) RunKeychainMigrate(ctx context.Context, in *RunKeychainMigrateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DesktopService_ServiceDesc.Streams[3], DesktopService_RunKeychainMigrate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunKeychainMigrateRequest, ProgressEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DesktopService_RunKeychainMigrateClient = grpc.ServerStreamingClient[ProgressEvent]

func (c *desktopServiceClient) SubscribeActive(ctx context.Context, in *SubscribeActiveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DesktopService_ServiceDesc.Streams[4], DesktopService_SubscribeActive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeActiveRequest, ProgressEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DesktopService_SubscribeActiveClient = grpc.ServerStreamingClient[ProgressEvent]

func (c *desktopServiceClient) GetUpdaterStatus(ctx context.Context, in *GetUpdaterStatusRequest, opts ...grpc.CallOption) (*GetUpdaterStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUpdaterStatusResponse)
	err := c.cc.Invoke(ctx, DesktopService_GetUpdaterStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DesktopServiceServer is the server API for DesktopService service.
// All implementations should embed UnimplementedDesktopServiceServer
// for forward compatibility.
//
// DesktopService is the daemon control plane. The daemon owns all operation
// logic; the CLI is a thin client that invokes these RPCs and renders the
// streamed ProgressEvent values through the same live model used for local
// runs. A Run* call either starts the operation or, when one is already in
// flight for the same target and operation, streams that run's events instead.
// Distinct targets can run at the same time, while conflicting mutations for
// the same target are rejected.
type DesktopServiceServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	RunUpgrade(*RunUpgradeRequest, grpc.ServerStreamingServer[ProgressEvent]) error
	RunPatch(*RunPatchRequest, grpc.ServerStreamingServer[ProgressEvent]) error
	RunHardReset(*RunHardResetRequest, grpc.ServerStreamingServer[ProgressEvent]) error
	RunKeychainMigrate(*RunKeychainMigrateRequest, grpc.ServerStreamingServer[ProgressEvent]) error
	SubscribeActive(*SubscribeActiveRequest, grpc.ServerStreamingServer[ProgressEvent]) error
	GetUpdaterStatus(context.Context, *GetUpdaterStatusRequest) (*GetUpdaterStatusResponse, error)
}

// UnimplementedDesktopServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDesktopServiceServer struct{}

func (UnimplementedDesktopServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedDesktopServiceServer) RunUpgrade(*RunUpgradeRequest, grpc.ServerStreamingServer[ProgressEvent]) error {
	return status.Error(codes.Unimplemented, "method RunUpgrade not implemented")
}
func (UnimplementedDesktopServiceServer) RunPatch(*RunPatchRequest, grpc.ServerStreamingServer[ProgressEvent]) error {
	return status.Error(codes.Unimplemented, "method RunPatch not implemented")
}
func (UnimplementedDesktopServiceServer) RunHardReset(*RunHardResetRequest, grpc.ServerStreamingServer[ProgressEvent]) error {
	return status.Error(codes.Unimplemented, "method RunHardReset not implemented")
}
func (UnimplementedDesktopServiceServer) RunKeychainMigrate(*RunKeychainMigrateRequest, grpc.ServerStreamingServer[ProgressEvent]) error {
	return status.Error(codes.Unimplemented, "method RunKeychainMigrate not implemented")
}
func (UnimplementedDesktopServiceServer) SubscribeActive(*SubscribeActiveRequest, grpc.ServerStreamingServer[ProgressEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeActive not implemented")
}
func (UnimplementedDesktopServiceServer) GetUpdaterStatus(context.Context, *GetUpdaterStatusRequest) (*GetUpdaterStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUpdaterStatus not implemented")
}
func (UnimplementedDesktopServiceServer) testEmbeddedByValue() {}

// UnsafeDesktopServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DesktopServiceServer will
// result in compilation errors.
type UnsafeDesktopServiceServer interface {
	mustEmbedUnimplementedDesktopServiceServer()
}

func RegisterDesktopServiceServer(s grpc.ServiceRegistrar, srv DesktopServiceServer) {
	// If the following call panics, it indicates UnimplementedDesktopServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DesktopService_ServiceDesc, srv)
}

func _DesktopService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopService_RunUpgrade_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunUpgradeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DesktopServiceServer).RunUpgrade(m, &grpc.GenericServerStream[RunUpgradeRequest, ProgressEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DesktopService_RunUpgradeServer = grpc.ServerStreamingServer[ProgressEvent]

func _DesktopService_RunPatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunPatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DesktopServiceServer).RunPatch(m, &grpc.GenericServerStream[RunPatchRequest, ProgressEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DesktopService_RunPatchServer = grpc.ServerStreamingServer[ProgressEvent]

func _DesktopService_RunHardReset_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunHardResetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DesktopServiceServer).RunHardReset(m, &grpc.GenericServerStream[RunHardResetRequest, ProgressEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DesktopService_RunHardResetServer = grpc.ServerStreamingServer[ProgressEvent]

func _DesktopService_RunKeychainMigrate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunKeychainMigrateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DesktopServiceServer).RunKeychainMigrate(m, &grpc.GenericServerStream[RunKeychainMigrateRequest, ProgressEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DesktopService_RunKeychainMigrateServer = grpc.ServerStreamingServer[ProgressEvent]

func _DesktopService_SubscribeActive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeActiveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DesktopServiceServer).SubscribeActive(m, &grpc.GenericServerStream[SubscribeActiveRequest, ProgressEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DesktopService_SubscribeActiveServer = grpc.ServerStreamingServer[ProgressEvent]

func _DesktopService_GetUpdaterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUpdaterStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopServiceServer).GetUpdaterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopService_GetUpdaterStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopServiceServer).GetUpdaterStatus(ctx, req.(*GetUpdaterStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DesktopService_ServiceDesc is the grpc.ServiceDesc for DesktopService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DesktopService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "desktopviaclyde.v1.DesktopService",
	HandlerType: (*DesktopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _DesktopService_GetStatus_Handler,
		},
		{
			MethodName: "GetUpdaterStatus",
			Handler:    _DesktopService_GetUpdaterStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunUpgrade",
			Handler:       _DesktopService_RunUpgrade_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RunPatch",
			Handler:       _DesktopService_RunPatch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RunHardReset",
			Handler:       _DesktopService_RunHardReset_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RunKeychainMigrate",
			Handler:       _DesktopService_RunKeychainMigrate_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeActive",
			Handler:       _DesktopService_SubscribeActive_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "desktopviaclyde/v1/daemon/service.proto",
}
