// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: desktopviaclyde/v1/daemon/service.proto

package desktopviaclydev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProgressEvent mirrors internal/clioutput.Event field-for-field so the client
// renders a streamed run with the unchanged live model. The optional scalars
// map to the pointer fields on Event.
type ProgressEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Step          string                 `protobuf:"bytes,4,opt,name=step,proto3" json:"step,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Detail        string                 `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
	Time          string                 `protobuf:"bytes,7,opt,name=time,proto3" json:"time,omitempty"`
	RunLog        string                 `protobuf:"bytes,8,opt,name=run_log,json=runLog,proto3" json:"run_log,omitempty"`
	LogFile       string                 `protobuf:"bytes,9,opt,name=log_file,json=logFile,proto3" json:"log_file,omitempty"`
	DryRun        *bool                  `protobuf:"varint,10,opt,name=dry_run,json=dryRun,proto3,oneof" json:"dry_run,omitempty"`
	Parallel      *int32                 `protobuf:"varint,11,opt,name=parallel,proto3,oneof" json:"parallel,omitempty"`
	DurationMs    *int64                 `protobuf:"varint,12,opt,name=duration_ms,json=durationMs,proto3,oneof" json:"duration_ms,omitempty"`
	Succeeded     *int32                 `protobuf:"varint,13,opt,name=succeeded,proto3,oneof" json:"succeeded,omitempty"`
	Failed        *int32                 `protobuf:"varint,14,opt,name=failed,proto3,oneof" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressEvent) Reset() {
	*x = ProgressEvent{}
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressEvent) ProtoMessage() {}

func (x *ProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressEvent.ProtoReflect.Descriptor instead.
func (*ProgressEvent) Descriptor() ([]byte, []int) {
	return file_desktopviaclyde_v1_daemon_service_proto_rawDescGZIP(), []int{0}
}

func (x *ProgressEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProgressEvent) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ProgressEvent) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ProgressEvent) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *ProgressEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProgressEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ProgressEvent) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *ProgressEvent) GetRunLog() string {
	if x != nil {
		return x.RunLog
	}
	return ""
}

func (x *ProgressEvent) GetLogFile() string {
	if x != nil {
		return x.LogFile
	}
	return ""
}

func (x *ProgressEvent) GetDryRun() bool {
	if x != nil && x.DryRun != nil {
		return *x.DryRun
	}
	return false
}

func (x *ProgressEvent) GetParallel() int32 {
	if x != nil && x.Parallel != nil {
		return *x.Parallel
	}
	return 0
}

func (x *ProgressEvent) GetDurationMs() int64 {
	if x != nil && x.DurationMs != nil {
		return *x.DurationMs
	}
	return 0
}

func (x *ProgressEvent) GetSucceeded() int32 {
	if x != nil && x.Succeeded != nil {
		return *x.Succeeded
	}
	return 0
}

func (x *ProgressEvent) GetFailed() int32 {
	if x != nil && x.Failed != nil {
		return *x.Failed
	}
	return 0
}

// OperationFlags carries the parsed CLI flag values for one operation, matching
// internal/operations.FlagValues (a string map and a bool map).
type OperationFlags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strings       map[string]string      `protobuf:"bytes,1,rep,name=strings,proto3" json:"strings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Bools         map[string]bool        `protobuf:"bytes,2,rep,name=bools,proto3" json:"bools,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationFlags) Reset() {
	*x = OperationFlags{}
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationFlags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationFlags) ProtoMessage() {}

func (x *OperationFlags) ProtoReflect() protoreflect.Message {
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationFlags.ProtoReflect.Descriptor instead.
func (*OperationFlags) Descriptor() ([]byte, []int) {
	return file_desktopviaclyde_v1_daemon_service_proto_rawDescGZIP(), []int{1}
}

func (x *OperationFlags) GetStrings() map[string]string {
	if x != nil {
		return x.Strings
	}
	return nil
}

func (x *OperationFlags) GetBools() map[string]bool {
	if x != nil {
		return x.Bools
	}
	return nil
}

// RunUpgradeRequest asks the daemon to upgrade one configured target.
type RunUpgradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Flags         *OperationFlags        `protobuf:"bytes,3,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunUpgradeRequest) Reset() {
	*x = RunUpgradeRequest{}
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunUpgradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunUpgradeRequest) ProtoMessage() {}

func (x *RunUpgradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunUpgradeRequest.ProtoReflect.Descriptor instead.
func (*RunUpgradeRequest) Descriptor() ([]byte, []int) {
	return file_desktopviaclyde_v1_daemon_service_proto_rawDescGZIP(), []int{2}
}

func (x *RunUpgradeRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RunUpgradeRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *RunUpgradeRequest) GetFlags() *OperationFlags {
	if x != nil {
		return x.Flags
	}
	return nil
}

// RunPatchRequest asks the daemon to patch one configured target.
type RunPatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Flags         *OperationFlags        `protobuf:"bytes,3,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPatchRequest) Reset() {
	*x = RunPatchRequest{}
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPatchRequest) ProtoMessage() {}

func (x *RunPatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPatchRequest.ProtoReflect.Descriptor instead.
func (*RunPatchRequest) Descriptor() ([]byte, []int) {
	return file_desktopviaclyde_v1_daemon_service_proto_rawDescGZIP(), []int{3}
}

func (x *RunPatchRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RunPatchRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *RunPatchRequest) GetFlags() *OperationFlags {
	if x != nil {
		return x.Flags
	}
	return nil
}

// RunHardResetRequest asks the daemon to hard-reset one configured target.
type RunHardResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Flags         *OperationFlags        `protobuf:"bytes,3,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunHardResetRequest) Reset() {
	*x = RunHardResetRequest{}
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunHardResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunHardResetRequest) ProtoMessage() {}

func (x *RunHardResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunHardResetRequest.ProtoReflect.Descriptor instead.
func (*RunHardResetRequest) Descriptor() ([]byte, []int) {
	return file_desktopviaclyde_v1_daemon_service_proto_rawDescGZIP(), []int{4}
}

func (x *RunHardResetRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RunHardResetRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *RunHardResetRequest) GetFlags() *OperationFlags {
	if x != nil {
		return x.Flags
	}
	return nil
}

// RunKeychainMigrateRequest asks the daemon to restore keychain access for one
// configured target.
type RunKeychainMigrateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Flags         *OperationFlags        `protobuf:"bytes,3,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunKeychainMigrateRequest) Reset() {
	*x = RunKeychainMigrateRequest{}
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunKeychainMigrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunKeychainMigrateRequest) ProtoMessage() {}

func (x *RunKeychainMigrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunKeychainMigrateRequest.ProtoReflect.Descriptor instead.
func (*RunKeychainMigrateRequest) Descriptor() ([]byte, []int) {
	return file_desktopviaclyde_v1_daemon_service_proto_rawDescGZIP(), []int{5}
}

func (x *RunKeychainMigrateRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RunKeychainMigrateRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *RunKeychainMigrateRequest) GetFlags() *OperationFlags {
	if x != nil {
		return x.Flags
	}
	return nil
}

// SubscribeActiveRequest attaches to active runs, optionally filtered by
// operation and target. It completes immediately when no matching operation is
// in flight.
type SubscribeActiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeActiveRequest) Reset() {
	*x = SubscribeActiveRequest{}
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeActiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeActiveRequest) ProtoMessage() {}

func (x *SubscribeActiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeActiveRequest.ProtoReflect.Descriptor instead.
func (*SubscribeActiveRequest) Descriptor() ([]byte, []int) {
	return file_desktopviaclyde_v1_daemon_service_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeActiveRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *SubscribeActiveRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// GetStatusRequest asks for the per-target patched state report.
type GetStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target is one configured target id, or empty for every target.
	Target        string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_desktopviaclyde_v1_daemon_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetStatusRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// GetStatusResponse carries the serialized internal/statusreport.Report so the
// client renders it as text or passes the JSON through unchanged.
type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportJson    string                 `protobuf:"bytes,1,opt,name=report_json,json=reportJson,proto3" json:"report_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_desktopviaclyde_v1_daemon_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetStatusResponse) GetReportJson() string {
	if x != nil {
		return x.ReportJson
	}
	return ""
}

// GetUpdaterStatusRequest asks for the upgrade tick loop's current state.
type GetUpdaterStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpdaterStatusRequest) Reset() {
	*x = GetUpdaterStatusRequest{}
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdaterStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdaterStatusRequest) ProtoMessage() {}

func (x *GetUpdaterStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdaterStatusRequest.ProtoReflect.Descriptor instead.
func (*GetUpdaterStatusRequest) Descriptor() ([]byte, []int) {
	return file_desktopviaclyde_v1_daemon_service_proto_rawDescGZIP(), []int{9}
}

// GetUpdaterStatusResponse reports the tick loop state and the last per-target
// upgrade check.
type GetUpdaterStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Running         bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	ActiveOperation string                 `protobuf:"bytes,2,opt,name=active_operation,json=activeOperation,proto3" json:"active_operation,omitempty"`
	ActiveTarget    string                 `protobuf:"bytes,3,opt,name=active_target,json=activeTarget,proto3" json:"active_target,omitempty"`
	LastTickUnix    int64                  `protobuf:"varint,4,opt,name=last_tick_unix,json=lastTickUnix,proto3" json:"last_tick_unix,omitempty"`
	NextTickUnix    int64                  `protobuf:"varint,5,opt,name=next_tick_unix,json=nextTickUnix,proto3" json:"next_tick_unix,omitempty"`
	IntervalSeconds int64                  `protobuf:"varint,6,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	Targets         []*UpdaterTargetStatus `protobuf:"bytes,7,rep,name=targets,proto3" json:"targets,omitempty"`
	ActiveRuns      []*ActiveRun           `protobuf:"bytes,8,rep,name=active_runs,json=activeRuns,proto3" json:"active_runs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUpdaterStatusResponse) Reset() {
	*x = GetUpdaterStatusResponse{}
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdaterStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdaterStatusResponse) ProtoMessage() {}

func (x *GetUpdaterStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdaterStatusResponse.ProtoReflect.Descriptor instead.
func (*GetUpdaterStatusResponse) Descriptor() ([]byte, []int) {
	return file_desktopviaclyde_v1_daemon_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetUpdaterStatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *GetUpdaterStatusResponse) GetActiveOperation() string {
	if x != nil {
		return x.ActiveOperation
	}
	return ""
}

func (x *GetUpdaterStatusResponse) GetActiveTarget() string {
	if x != nil {
		return x.ActiveTarget
	}
	return ""
}

func (x *GetUpdaterStatusResponse) GetLastTickUnix() int64 {
	if x != nil {
		return x.LastTickUnix
	}
	return 0
}

func (x *GetUpdaterStatusResponse) GetNextTickUnix() int64 {
	if x != nil {
		return x.NextTickUnix
	}
	return 0
}

func (x *GetUpdaterStatusResponse) GetIntervalSeconds() int64 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *GetUpdaterStatusResponse) GetTargets() []*UpdaterTargetStatus {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *GetUpdaterStatusResponse) GetActiveRuns() []*ActiveRun {
	if x != nil {
		return x.ActiveRuns
	}
	return nil
}

type ActiveRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveRun) Reset() {
	*x = ActiveRun{}
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveRun) ProtoMessage() {}

func (x *ActiveRun) ProtoReflect() protoreflect.Message {
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveRun.ProtoReflect.Descriptor instead.
func (*ActiveRun) Descriptor() ([]byte, []int) {
	return file_desktopviaclyde_v1_daemon_service_proto_rawDescGZIP(), []int{11}
}

func (x *ActiveRun) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ActiveRun) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// UpdaterTargetStatus is the last upgrade-check outcome for one target.
type UpdaterTargetStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Target           string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	CurrentVersion   string                 `protobuf:"bytes,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	AvailableVersion string                 `protobuf:"bytes,3,opt,name=available_version,json=availableVersion,proto3" json:"available_version,omitempty"`
	UpdateAvailable  bool                   `protobuf:"varint,4,opt,name=update_available,json=updateAvailable,proto3" json:"update_available,omitempty"`
	AppRunning       bool                   `protobuf:"varint,5,opt,name=app_running,json=appRunning,proto3" json:"app_running,omitempty"`
	LastOutcome      string                 `protobuf:"bytes,6,opt,name=last_outcome,json=lastOutcome,proto3" json:"last_outcome,omitempty"`
	LastCheckedUnix  int64                  `protobuf:"varint,7,opt,name=last_checked_unix,json=lastCheckedUnix,proto3" json:"last_checked_unix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdaterTargetStatus) Reset() {
	*x = UpdaterTargetStatus{}
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdaterTargetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdaterTargetStatus) ProtoMessage() {}

func (x *UpdaterTargetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_desktopviaclyde_v1_daemon_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdaterTargetStatus.ProtoReflect.Descriptor instead.
func (*UpdaterTargetStatus) Descriptor() ([]byte, []int) {
	return file_desktopviaclyde_v1_daemon_service_proto_rawDescGZIP(), []int{12}
}

func (x *UpdaterTargetStatus) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *UpdaterTargetStatus) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

func (x *UpdaterTargetStatus) GetAvailableVersion() string {
	if x != nil {
		return x.AvailableVersion
	}
	return ""
}

func (x *UpdaterTargetStatus) GetUpdateAvailable() bool {
	if x != nil {
		return x.UpdateAvailable
	}
	return false
}

func (x *UpdaterTargetStatus) GetAppRunning() bool {
	if x != nil {
		return x.AppRunning
	}
	return false
}

func (x *UpdaterTargetStatus) GetLastOutcome() string {
	if x != nil {
		return x.LastOutcome
	}
	return ""
}

func (x *UpdaterTargetStatus) GetLastCheckedUnix() int64 {
	if x != nil {
		return x.LastCheckedUnix
	}
	return 0
}

var File_desktopviaclyde_v1_daemon_service_proto protoreflect.FileDescriptor

const file_desktopviaclyde_v1_daemon_service_proto_rawDesc = "" +
	"\n" +
	"'desktopviaclyde/v1/daemon/service.proto\x12\x12desktopviaclyde.v1\"\xcc\x03\n" +
	"\rProgressEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x12\n" +
	"\x04step\x18\x04 \x01(\tR\x04step\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x16\n" +
	"\x06detail\x18\x06 \x01(\tR\x06detail\x12\x12\n" +
	"\x04time\x18\a \x01(\tR\x04time\x12\x17\n" +
	"\arun_log\x18\b \x01(\tR\x06runLog\x12\x19\n" +
	"\blog_file\x18\t \x01(\tR\alogFile\x12\x1c\n" +
	"\adry_run\x18\n" +
	" \x01(\bH\x00R\x06dryRun\x88\x01\x01\x12\x1f\n" +
	"\bparallel\x18\v \x01(\x05H\x01R\bparallel\x88\x01\x01\x12$\n" +
	"\vduration_ms\x18\f \x01(\x03H\x02R\n" +
	"durationMs\x88\x01\x01\x12!\n" +
	"\tsucceeded\x18\r \x01(\x05H\x03R\tsucceeded\x88\x01\x01\x12\x1b\n" +
	"\x06failed\x18\x0e \x01(\x05H\x04R\x06failed\x88\x01\x01B\n" +
	"\n" +
	"\b_dry_runB\v\n" +
	"\t_parallelB\x0e\n" +
	"\f_duration_msB\f\n" +
	"\n" +
	"_succeededB\t\n" +
	"\a_failed\"\x96\x02\n" +
	"\x0eOperationFlags\x12I\n" +
	"\astrings\x18\x01 \x03(\v2/.desktopviaclyde.v1.OperationFlags.StringsEntryR\astrings\x12C\n" +
	"\x05bools\x18\x02 \x03(\v2-.desktopviaclyde.v1.OperationFlags.BoolsEntryR\x05bools\x1a:\n" +
	"\fStringsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"BoolsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"}\n" +
	"\x11RunUpgradeRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x128\n" +
	"\x05flags\x18\x03 \x01(\v2\".desktopviaclyde.v1.OperationFlagsR\x05flags\"{\n" +
	"\x0fRunPatchRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x128\n" +
	"\x05flags\x18\x03 \x01(\v2\".desktopviaclyde.v1.OperationFlagsR\x05flags\"\x7f\n" +
	"\x13RunHardResetRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x128\n" +
	"\x05flags\x18\x03 \x01(\v2\".desktopviaclyde.v1.OperationFlagsR\x05flags\"\x85\x01\n" +
	"\x19RunKeychainMigrateRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x128\n" +
	"\x05flags\x18\x03 \x01(\v2\".desktopviaclyde.v1.OperationFlagsR\x05flags\"N\n" +
	"\x16SubscribeActiveRequest\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\"*\n" +
	"\x10GetStatusRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"4\n" +
	"\x11GetStatusResponse\x12\x1f\n" +
	"\vreport_json\x18\x01 \x01(\tR\n" +
	"reportJson\"\x19\n" +
	"\x17GetUpdaterStatusRequest\"\xfe\x02\n" +
	"\x18GetUpdaterStatusResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12)\n" +
	"\x10active_operation\x18\x02 \x01(\tR\x0factiveOperation\x12#\n" +
	"\ractive_target\x18\x03 \x01(\tR\factiveTarget\x12$\n" +
	"\x0elast_tick_unix\x18\x04 \x01(\x03R\flastTickUnix\x12$\n" +
	"\x0enext_tick_unix\x18\x05 \x01(\x03R\fnextTickUnix\x12)\n" +
	"\x10interval_seconds\x18\x06 \x01(\x03R\x0fintervalSeconds\x12A\n" +
	"\atargets\x18\a \x03(\v2'.desktopviaclyde.v1.UpdaterTargetStatusR\atargets\x12>\n" +
	"\vactive_runs\x18\b \x03(\v2\x1d.desktopviaclyde.v1.ActiveRunR\n" +
	"activeRuns\"A\n" +
	"\tActiveRun\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\"\x9e\x02\n" +
	"\x13UpdaterTargetStatus\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\tR\x0ecurrentVersion\x12+\n" +
	"\x11available_version\x18\x03 \x01(\tR\x10availableVersion\x12)\n" +
	"\x10update_available\x18\x04 \x01(\bR\x0fupdateAvailable\x12\x1f\n" +
	"\vapp_running\x18\x05 \x01(\bR\n" +
	"appRunning\x12!\n" +
	"\flast_outcome\x18\x06 \x01(\tR\vlastOutcome\x12*\n" +
	"\x11last_checked_unix\x18\a \x01(\x03R\x0flastCheckedUnix2\xb5\x05\n" +
	"\x0eDesktopService\x12X\n" +
	"\tGetStatus\x12$.desktopviaclyde.v1.GetStatusRequest\x1a%.desktopviaclyde.v1.GetStatusResponse\x12X\n" +
	"\n" +
	"RunUpgrade\x12%.desktopviaclyde.v1.RunUpgradeRequest\x1a!.desktopviaclyde.v1.ProgressEvent0\x01\x12T\n" +
	"\bRunPatch\x12#.desktopviaclyde.v1.RunPatchRequest\x1a!.desktopviaclyde.v1.ProgressEvent0\x01\x12\\\n" +
	"\fRunHardReset\x12'.desktopviaclyde.v1.RunHardResetRequest\x1a!.desktopviaclyde.v1.ProgressEvent0\x01\x12h\n" +
	"\x12RunKeychainMigrate\x12-.desktopviaclyde.v1.RunKeychainMigrateRequest\x1a!.desktopviaclyde.v1.ProgressEvent0\x01\x12b\n" +
	"\x0fSubscribeActive\x12*.desktopviaclyde.v1.SubscribeActiveRequest\x1a!.desktopviaclyde.v1.ProgressEvent0\x01\x12m\n" +
	"\x10GetUpdaterStatus\x12+.desktopviaclyde.v1.GetUpdaterStatusRequest\x1a,.desktopviaclyde.v1.GetUpdaterStatusResponseBHZFgoodkind.io/desktop-via-clyde/api/desktopviaclyde/v1;desktopviaclydev1b\x06proto3"

var (
	file_desktopviaclyde_v1_daemon_service_proto_rawDescOnce sync.Once
	file_desktopviaclyde_v1_daemon_service_proto_rawDescData []byte
)

func file_desktopviaclyde_v1_daemon_service_proto_rawDescGZIP() []byte {
	file_desktopviaclyde_v1_daemon_service_proto_rawDescOnce.Do(func() {
		file_desktopviaclyde_v1_daemon_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_desktopviaclyde_v1_daemon_service_proto_rawDesc), len(file_desktopviaclyde_v1_daemon_service_proto_rawDesc)))
	})
	return file_desktopviaclyde_v1_daemon_service_proto_rawDescData
}

var file_desktopviaclyde_v1_daemon_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_desktopviaclyde_v1_daemon_service_proto_goTypes = []any{
	(*ProgressEvent)(nil),             // 0: desktopviaclyde.v1.ProgressEvent
	(*OperationFlags)(nil),            // 1: desktopviaclyde.v1.OperationFlags
	(*RunUpgradeRequest)(nil),         // 2: desktopviaclyde.v1.RunUpgradeRequest
	(*RunPatchRequest)(nil),           // 3: desktopviaclyde.v1.RunPatchRequest
	(*RunHardResetRequest)(nil),       // 4: desktopviaclyde.v1.RunHardResetRequest
	(*RunKeychainMigrateRequest)(nil), // 5: desktopviaclyde.v1.RunKeychainMigrateRequest
	(*SubscribeActiveRequest)(nil),    // 6: desktopviaclyde.v1.SubscribeActiveRequest
	(*GetStatusRequest)(nil),          // 7: desktopviaclyde.v1.GetStatusRequest
	(*GetStatusResponse)(nil),         // 8: desktopviaclyde.v1.GetStatusResponse
	(*GetUpdaterStatusRequest)(nil),   // 9: desktopviaclyde.v1.GetUpdaterStatusRequest
	(*GetUpdaterStatusResponse)(nil),  // 10: desktopviaclyde.v1.GetUpdaterStatusResponse
	(*ActiveRun)(nil),                 // 11: desktopviaclyde.v1.ActiveRun
	(*UpdaterTargetStatus)(nil),       // 12: desktopviaclyde.v1.UpdaterTargetStatus
	nil,                               // 13: desktopviaclyde.v1.OperationFlags.StringsEntry
	nil,                               // 14: desktopviaclyde.v1.OperationFlags.BoolsEntry
}
var file_desktopviaclyde_v1_daemon_service_proto_depIdxs = []int32{
	13, // 0: desktopviaclyde.v1.OperationFlags.strings:type_name -> desktopviaclyde.v1.OperationFlags.StringsEntry
	14, // 1: desktopviaclyde.v1.OperationFlags.bools:type_name -> desktopviaclyde.v1.OperationFlags.BoolsEntry
	1,  // 2: desktopviaclyde.v1.RunUpgradeRequest.flags:type_name -> desktopviaclyde.v1.OperationFlags
	1,  // 3: desktopviaclyde.v1.RunPatchRequest.flags:type_name -> desktopviaclyde.v1.OperationFlags
	1,  // 4: desktopviaclyde.v1.RunHardResetRequest.flags:type_name -> desktopviaclyde.v1.OperationFlags
	1,  // 5: desktopviaclyde.v1.RunKeychainMigrateRequest.flags:type_name -> desktopviaclyde.v1.OperationFlags
	12, // 6: desktopviaclyde.v1.GetUpdaterStatusResponse.targets:type_name -> desktopviaclyde.v1.UpdaterTargetStatus
	11, // 7: desktopviaclyde.v1.GetUpdaterStatusResponse.active_runs:type_name -> desktopviaclyde.v1.ActiveRun
	7,  // 8: desktopviaclyde.v1.DesktopService.GetStatus:input_type -> desktopviaclyde.v1.GetStatusRequest
	2,  // 9: desktopviaclyde.v1.DesktopService.RunUpgrade:input_type -> desktopviaclyde.v1.RunUpgradeRequest
	3,  // 10: desktopviaclyde.v1.DesktopService.RunPatch:input_type -> desktopviaclyde.v1.RunPatchRequest
	4,  // 11: desktopviaclyde.v1.DesktopService.RunHardReset:input_type -> desktopviaclyde.v1.RunHardResetRequest
	5,  // 12: desktopviaclyde.v1.DesktopService.RunKeychainMigrate:input_type -> desktopviaclyde.v1.RunKeychainMigrateRequest
	6,  // 13: desktopviaclyde.v1.DesktopService.SubscribeActive:input_type -> desktopviaclyde.v1.SubscribeActiveRequest
	9,  // 14: desktopviaclyde.v1.DesktopService.GetUpdaterStatus:input_type -> desktopviaclyde.v1.GetUpdaterStatusRequest
	8,  // 15: desktopviaclyde.v1.DesktopService.GetStatus:output_type -> desktopviaclyde.v1.GetStatusResponse
	0,  // 16: desktopviaclyde.v1.DesktopService.RunUpgrade:output_type -> desktopviaclyde.v1.ProgressEvent
	0,  // 17: desktopviaclyde.v1.DesktopService.RunPatch:output_type -> desktopviaclyde.v1.ProgressEvent
	0,  // 18: desktopviaclyde.v1.DesktopService.RunHardReset:output_type -> desktopviaclyde.v1.ProgressEvent
	0,  // 19: desktopviaclyde.v1.DesktopService.RunKeychainMigrate:output_type -> desktopviaclyde.v1.ProgressEvent
	0,  // 20: desktopviaclyde.v1.DesktopService.SubscribeActive:output_type -> desktopviaclyde.v1.ProgressEvent
	10, // 21: desktopviaclyde.v1.DesktopService.GetUpdaterStatus:output_type -> desktopviaclyde.v1.GetUpdaterStatusResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_desktopviaclyde_v1_daemon_service_proto_init() }
func file_desktopviaclyde_v1_daemon_service_proto_init() {
	if File_desktopviaclyde_v1_daemon_service_proto != nil {
		return
	}
	file_desktopviaclyde_v1_daemon_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_desktopviaclyde_v1_daemon_service_proto_rawDesc), len(file_desktopviaclyde_v1_daemon_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_desktopviaclyde_v1_daemon_service_proto_goTypes,
		DependencyIndexes: file_desktopviaclyde_v1_daemon_service_proto_depIdxs,
		MessageInfos:      file_desktopviaclyde_v1_daemon_service_proto_msgTypes,
	}.Build()
	File_desktopviaclyde_v1_daemon_service_proto = out.File
	file_desktopviaclyde_v1_daemon_service_proto_goTypes = nil
	file_desktopviaclyde_v1_daemon_service_proto_depIdxs = nil
}
