// Code generated by desktop-via-clyde Bubble Tea adapter generation. DO NOT EDIT.

package clioutput

import (
	tea "github.com/charmbracelet/bubbletea"
)

type bubbleLiveModel struct {
	model *liveModel
}

func newBubbleLiveModel(model *liveModel) *bubbleLiveModel {
	return &bubbleLiveModel{model: model}
}

func (m *bubbleLiveModel) Init() tea.Cmd {
	return nil
}

func (m *bubbleLiveModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch typed := msg.(type) {
	case eventMsg:
		m.model.apply(typed.Event)
		return m, nil
	case closeMsg:
		return m, tea.Quit
	default:
		return m, nil
	}
}

func (m *bubbleLiveModel) View() string {
	return m.model.View()
}
